# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wool < Formula
  desc "Wool is a cloud control plane as a service."
  homepage "https://wool.dev"
  version "0.0.1-next.3"
  license "cannot_represent"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/wool-dev/wool/releases/download/v0.0.1-next.3/wool_Darwin_arm64.tar.gz"
      sha256 "21e39a25904059522d92543e1b4aba7852d6e31f049320104eab01adfb0d0f4b"

      def install
        bin.install "wool"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/wool-dev/wool/releases/download/v0.0.1-next.3/wool_Linux_x86_64.tar.gz"
      sha256 "007b0dde2ab6ab852cf717333d7fa6b5bfba064e84ab60f05487fa7cedc4646a"

      def install
        bin.install "wool"
      end
    end
  end

  test do
    system "#{bin}/wool", "version"
  end
end
