# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wool < Formula
  desc "Wool is a cloud for developers."
  homepage "https://wool.dev"
  version "0.1.8"
  license ":cannot_represent"

  depends_on "buildpacks/tap/pack"

  on_macos do
    if Hardware::CPU.arm?
      url "https://wool-sandbox-aws1-releases.s3.amazonaws.com/wool/v0.1.8/wool_Darwin_arm64.tar.gz"
      sha256 "26690086527f07fe64c3039025092776f65da0891e2c132e0d898fc780027e26"

      def install
        bin.install "wool"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://wool-sandbox-aws1-releases.s3.amazonaws.com/wool/v0.1.8/wool_Linux_x86_64.tar.gz"
      sha256 "6ccdb96c2fd8beedcaebb47a113d187b7aad4f37aec553f707b207fb1ad3b40d"

      def install
        bin.install "wool"
      end
    end
  end

  test do
    system "#{bin}/wool", "version"
  end
end
