# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wool < Formula
  desc "Wool is a cloud for developers."
  homepage "https://wool.dev"
  version "0.1.9"
  license ":cannot_represent"

  depends_on "buildpacks/tap/pack"

  on_macos do
    if Hardware::CPU.arm?
      url "https://wool-sandbox-aws1-releases.s3.amazonaws.com/wool/v0.1.9/wool_Darwin_arm64.tar.gz"
      sha256 "b4da62d2e9076a6264ce4763ad1ad8cab3a6657e249ecdb4af4ef337e82a61b3"

      def install
        bin.install "wool"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://wool-sandbox-aws1-releases.s3.amazonaws.com/wool/v0.1.9/wool_Linux_x86_64.tar.gz"
      sha256 "2e59676da91d3f5c6c0849fecf8b8d827d35d5bee9d4ad224e32880c3f2459c9"

      def install
        bin.install "wool"
      end
    end
  end

  test do
    system "#{bin}/wool", "version"
  end
end
